### ISSUE TITLE
Page links aren't centred properly

### ISSUE THREAD

**Issue by cjwatson** [canonical-ols/build.snapcraft.io#118]
The page links on the repository list aren't centred relative to the repositories below them:

![page-links-not-centred](https://cloud.githubusercontent.com/assets/2429141/22823462/a50dfb80-ef7b-11e6-96b3-c8f6144282d8.png)

**Comment by bartaz** [comment]
Interesting... Because I don't see repo names centered (they haven't been when I made the list).

<img width="972" alt="screen shot 2017-02-10 at 12 06 44" src="https://cloud.githubusercontent.com/assets/83575/22824750/958e852c-ef89-11e6-852a-e5a902147c8e.png">


And pagination is likely centred along whole line (including the button), that's why it seems off.

**Comment by cjwatson** [comment]
I definitely prefer the look of the left-aligned repository names.  (And yes, I know this will all change soon anyway.)

**Comment by evandandrea** [comment]
Closing this out. The UI has moved on significantly.
