### ISSUE TITLE
Can't select public organisation repositories

### ISSUE THREAD

**Issue by didrocks** [canonical-ols/build.snapcraft.io#132]
On login, build.snapcraft.io asks github to have access to user's and related organization's repositories. However, even if this access is granted, it seems it's only listing the user's repository on the select repo page.

(For instance, I granted access to "didrocks" and "ubuntu" github repos and only see "didrocks/*"

**Comment by cjwatson** [comment]
On 14 February 2017 15:51:33 GMT+00:00, Didier Roche <notifications@github.com> wrote:
>On login, build.snapcraft.io asks github to have access to user's and
>related organization's repositories. However, even if this access is
>granted, it seems it's only listing the user's repository on the select
>repo page.
>
>(For instance, I granted access to "didrocks" and "ubuntu" github repos
>and only see "didrocks/*"

Indeed, we haven't implemented that yet.  (No harm having a bug open for it, though.)
-- 
Colin Watson

**Comment by cjwatson** [comment]
Users will have to have admin permissions on the repository in order to install webhooks, which will probably only cover a subset of the organisation-owned repositories that they can push to.  (I think this is fine because publishing a snap in some sense involves asserting ownership rather than just write access - see below - but it's worth being aware of.)

One design-level thing we should think about here is how to handle the question of ownership.  For a repository owned by a simple user account it's easy: the user owns their repository and nobody else does, so it's therefore fine for them to have sole ownership of the snap too.  For an organisation-owned repository it's more complicated.  If I enable `CanonicalLtd/foo` then presumably that repository should show up as enabled not just for me but for anyone else who has admin access to that repository.  But what about ownership of the snap in the store?  We have no reasonable way to map GitHub ownership onto store collaboration or similar.

Now, mostly this is OK because it'll just autobuild.  However, somebody might remove the snap and then try to re-add it, at which point they'll get a name conflict.  Or in future we might have a settings interface (e.g. which architectures are built); who would have access to that?  Maybe it's OK to just have the snap owned by whoever enabled it, but we should certainly think through the issues before painting ourselves into a corner.

**Comment by evandandrea** [comment]
@matthewpaulthomas and @carlaberkers, what are your thoughts on how organisations should be handled? We should also check how organisations work in other products that build on top of GitHub.

Personally, I would expect something like the following:

1. A developer with admin permissions on org-name/repo-name sets it up on build.snapcraft.io
1. As part of this set up, the developer registers the snap name under their just-created SSO account
- Any member of the organisation can see the repo on their dashboard and click through to build logs
- Any member of the organisation with admin permissions on the repo can remove the repo from the dashboard, but are warned that doing so will remove it for the entire organisation

If the developer creates a SSO account for hosting their organisation identity:

1. Developer reaches out and asks us to transfer the snap name to the SSO account for their organisation
1. We do so and make that developer a collaborator
- Only collaborators of the snap can publish to stable
- Where we offer stable publication instructions, non-collaborators are told to request collaborator status by emailing the address associated with the snap name (the organisation SSO account)
- We offer documentation for adding collaborators on the command line (pending APIs)

**Comment by matthewpaulthomas** [comment]
User stories to consider:
A. Adding a repo: conveying that you can’t add one if you have only read/write permissions.
B. Another admin adds/removes a repo that you’re an admin for: does it appear/disappear in your list?
C. Another admin deletes the repo from GitHub: do we need to convey what happened?
D. Another admin adds/removes the snapcraft.yaml: ditto.
E. Another admin registers/changes the snap name: ditto.
F. You give a repo a name that was previously registered, by another admin, for a since-removed/-renamed repo from the same organization: should this work?
G. A personal project becomes a professional one, so you try to give an organization repo a name that you previously registered for a since-removed/-renamed personal repo: should this work?
H. As an attacker, you try to give a personal repo a name that you previously registered for a since-removed/-renamed organization repo: should this work?
J. Someone else with write access triggers an automatic build: do we need to convey what happened any differently from if you triggered it yourself?
Z. Someone adds/changes a feature in build.snapcraft.io in future: how do we make sure organization repos are taken into account?

@evandandrea:
> If the developer creates a SSO account for hosting their organisation identity
>…
> We do so and make that developer a collaborator

If I understand this correctly, it implies (1) multi-user SSO accounts, and (2) tracking repo collaborators independently of GitHub. Can you explain the benefit of each? In particular, allowing multi-user SSO accounts seems like a lot of complexity in SSO, for the sake of Snapcraft organizational repos alone. For example:
- If one user changed the organization account’s password, (how) would the other users be notified?
- How would 2FA work? Would it expand from allowing two authentication devices per account, to allowing any number, 1+ for each admin of the repo?
- Does SSO have security checks to make sure, for example, that you aren’t signing in to the same account from the UK and Romania at the same time? If so, would distributed organizations need to disable this?

As an alternative, I suggest that any admin of a repo (as already tracked in GitHub) can see and change anything about the repo in Snapcraft. Then the only non-UI problems we need to solve are the name registration ones mentioned above (F, G, H).

**Comment by evandandrea** [comment]
@matthewpaulthomas 
>If I understand this correctly, it implies (1) multi-user SSO accounts, and (2) tracking repo collaborators independently of GitHub. Can you explain the benefit of each? In particular, allowing multi-user SSO accounts seems like a lot of complexity in SSO, for the sake of Snapcraft organizational repos alone.

I don't think the experience is sufficiently simple, but the only way I can see completely resolving it is relying on GitHub for organisation membership and organisation identity. And if we went that far, we might as well allow GitHub as an identity manager alongside SSO. That would require some convincing of the architects.

As you point out, SSO doesn't have a concept of organisations. We've skirted this by asking ISVs to create an SSO account solely to hold their identity. The username of that account is the brand name when you type `snap list`, e.g.
```
Name                Version                  Rev   Developer   Notes
docker              1.11.2-9                 56    docker-inc  -
```

Once created, the organisation SSO account does not need to be used for uploads. The developer portal has a page under each snap for "Collaborators", accounts that should see that snap as if it were their own, with uploads from that developer appearing as though they come from owner of the snap.

We have the ability to by-hand change the owner of snaps. So the path would be: developer owns, brand owns, developer is a collaborator. This of course would require guiding them to each of those steps, perhaps automating the whole as "I want to create or use a brand account to transfer this snap to."

It does not solve the problem that now you have to maintain your organisation membership in two-plus places: GitHub and the collaborator feature on every snap you maintain.

**Comment by evandandrea** [comment]
> cjwatson: ev: kind of depends whether you want organisation support in BSI now or next year really.
> cjwatson: multiple identity providers (and hence a more complex user namespace to avoid conflicts, etc.) would be a gigantic job
> cjwatson: also it's not clear that we would be able to use macaroons, which would throw a spanner into the works of every new endpoint we've built for snaps

**Comment by cjwatson** [comment]
Using GitHub as an identity provider would necessarily involve an intermediary that could deal with things like issuing macaroons.

There are various other possible options to bridge the gap.  I've thought of some non-exclusive possibilities, though I'm not pretending to have thought these through from start to finish, and each is probably controversial to some degree.  They're all likely to be less difficult than supporting multiple identity providers, though!

 - Add knowledge about GitHub to the store.  If it knows that a snap name is associated with a particular GitHub repository, and it knows the presenting user's GitHub identity, then it could treat that user as a collaborator if they have admin access to the relevant GitHub repository.
 - Add knowledge about a user's GitHub identity to SSO.  You'd do this by giving SSO some very minimal authorisation to your GitHub account, and then it would be able to assert something about your GitHub identity (be careful about renames) to the store.
 - Allow signing into an SSO account on the strength of being signed in to GitHub.  This is a bit different from the previous item because it would actually be an additional (or replacement) authentication method, and it certainly wouldn't be for everyone, but it could probably be constructed so that it would allow for eliminating a sign-in step.  Of course if you authenticated this way then SSO would obviously know your GitHub identity.  Signing up would still require selecting a separate username.
 - Refine the above by inventing a username namespace in SSO that's reserved for users authenticated by some other site, which (again, with thought given to renames) could allow for eliminating the separate username choice for sign-ups from GitHub.  In this model (and to a lesser extent in some of the previous options), SSO would be acting as a delegating identity provider.

Note that there is some prior art for delegated identity provision in parts of the Juju world, which we should look into if we decide to take that route.

**Comment by evandandrea** [comment]
Option one or two sound like a reasonable place to start, but I have two concerns:

- The snap ID will be tied to the GitHub user (via their SSO account) that created the snap name on build.snapcraft.io. If they leave the GitHub organisation, what happens?
- The presentation of the organisation name in `snap list` would be the aforementioned user's SSO username. @cjwatson do you have any thoughts on how we could instead map that to the organisation? Would caching the [org login field](https://api.github.com/orgs/azure) from GitHub be reasonable?

**Comment by evandandrea** [comment]
Some data:
> With almost 80M total Pull Requests on GitHub, we know that 85% of all requests for change come from within organizations. - https://octoverse.github.com

**Comment by cjwatson** [comment]
Those two concerns seem like basically different aspects of the same thing to me.

I think we really need people with more store knowledge than I do to weigh in on this (I asked @emgee to have a look the other day, so poking him again by way of this message).

IMO the ideal solution would be for the snap ID to in fact be tied to some representation of the GitHub organisation, but I don't know how hard that is.  One thing to remember is that we may well need this to be represented by way of assertions so that snapd can react appropriately to changes.

**Comment by cjwatson** [comment]
(One reason that gradually morphing SSO into a state where it can act as a sort of meta-identity-provider is appealing to me is that it would give us a namespace for the concept of "organisation whose membership is maintained by an external identity provider", which is otherwise tricky to model.)

**Comment by matthewpaulthomas** [comment]
In [the discussion document](https://docs.google.com/document/d/1skdkRgUP1CACua3zsWBchty9GnXv1UhDaUHUdI-wtxg/edit) I’ve placed wireframes for a bare-bones implementation: (a) when registering a snap name for an organization repo, you are guided to create, or sign in to, a shared SSO account for that organization, and (b) when renaming any snap you are first prompted, if necessary, to sign in to the account that registered the existing name. The UI design would be quite simple, but the interaction would be tedious, both for individuals and for distributed employees sharing that organization account.

It seems there’s no consensus on what to do beyond that, particularly how much the store could/should trust GitHub to track contributors securely.  So I’m not sure there’s more I can do at this point.

**Comment by nottrobin** [comment]
We had a meeting this morning to discuss how this task can be broken down into manageable sized tasks, and I've now created the cards that we decided from that meeting, which should be done roughly in this order:

1. #618: Confirm design specifications for organisations
2. #619: Allow users to sign-in to an SSO organisation account
3. #620: List organisation repositories on the "select repositories" page, so they can be added to the dashboard
4. #621: Tidy up attribution metrics to support organisation repositories
5. #622: Give user permission to collaborate on organisation snaps

We agreed to do #622 last because this allows us to provide a working implementation of organisations as early as possible - where users will simply need to sign in to the organisation account when they need that permission - and then add the smoother experience where sign-in is no longer necessary later on. @cjwatson suggested that splitting the work this way likely wouldn't add significant extra time. If this changes at any point, this decision can be revisited.

From the sounds of it the bulk of the work is currently contained in #619, and that should be broken down further as soon as we have a clearer idea of its implementation details from #618.

If I've missed any important information, or misunderstood any of the tasts in the way I've described them, please feel free to edit these issues or add new ones.

**Comment by evandandrea** [comment]
@nottrobin what do you think of closing this out, now that we've got a fresh set of GitHub issues tracking organisation repository support?

**Comment by nottrobin** [comment]
@evandandrea Yep, happy, to.
