### ISSUE TITLE
/login/failed is an inaccessible universal route

### ISSUE THREAD

**Issue by earnubs** [canonical-ols/build.snapcraft.io#133]
`/login/failed` is a universal route, but the user won't be able to reach it because the universal route handler redirects anyone without a session and team to login authenticate (https://github.com/canonical-ols/build.snapcraft.io/blob/master/src/server/handlers/universal.js#L33), which looks from the user point of view like nothing happened on sign in (user is quickly redirected from sso > bsi > sso)

**Comment by cjwatson** [comment]
The teams bit isn't quite as you describe it.  The reduced conditional is like this:

    const teams = JSON.parse(conf.get('OPENID_TEAMS') || 'null');
    ...
    if (!req.session && teams && teams.length) {
      res.redirect(302, '/login/authenticate');
    }

So it's not that the user is without a team, but that team membership information is expected from SSO.  It might be phrased as "if we need team membership information, and we don't have a session, then redirect".

I'm not sure how this could happen from SSO auth without the session being totally broken in some way, because it only redirects if there is a session (https://github.com/canonical-ols/build.snapcraft.io/blob/master/src/server/handlers/login.js#L130-L132).

It's probably not vital that we track this down, since the team-membership front-door is only temporary and will be removed next week anyway.

**Comment by earnubs** [comment]
Sorry, yes, I misread.  #135, was the real issue.
