### ISSUE TITLE
Homepages steps have inconsistent tense, and copy style problems

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#144]
The new homepage (created in #142 and based on [the design](https://projects.invisionapp.com/d/main/default/#/console/10245106/218034264/preview)) currently states:

- Push to GitHub.
- Built automatically.
- Published in the Snap Store

I understand the intention here, that it's trying to say "When you push to GitHub, your snap will be automatically built and published to the snap store", but to me these seem like 3 steps that either the user or the system are following, and so it's rather jarring to see the mixed tenses here.

Also, our [style guide](https://github.com/ubuntudesign/webteam-practices/blob/master/content/copy-reviews.md) states that list items (as I think these are) shouldn't have have full stops, and I'm not sure whether "Snap Store" should be capitalised, as "snap" generally isn't.

**Comment by bartaz** [comment]
@nottrobin Copy is from UX doc: https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#

I guess it would be best to discuss any changes there.

**Comment by nottrobin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix copy problems with homepage](https://trello.com/c/GFoR8zlT/151-fix-copy-problems-with-homepage)

**Comment by matthewpaulthomas** [comment]
Thanks to Robin for questioning this. Seven weeks later, though, I’m still happy with it as it is. It makes a distinction between what you the developer do and what Snapcraft the system does. This distinction is reflected in the illustration immediately above, where the first step shows you the developer and the other two steps don’t. If the change in tense gives you pause, I’d say that’s not a bug but a feature.

The full stops have been removed from the sentences on the grounds that they’re bulleted steps. I don’t think they are bulleted steps, but I don’t really care either way.

That “snap” isn’t capitalized doesn’t mean “snap store” shouldn’t be. (For example, compare “app” vs. “App Store”.) But apparently at the moment we don’t capitalize “snap store” anyway, so that has been fixed too.
