### ISSUE TITLE
Repos without a snapcraft.yaml trigger builds

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#225]
<img width="1034" alt="screen shot 2017-02-24 at 09 17 26" src="https://cloud.githubusercontent.com/assets/1523179/23297644/3130b944-fa72-11e6-8e95-cad60b5d0b44.png">

There's no snapcraft.yaml anywhere in evandandrea/dotfiles, but to my surprise that didn't stop builds from kicking off (which failed).

**Comment by cjwatson** [comment]
This is because we're still setting `auto_build: true` when we initially create the snap, which is basically a leftover of how we used to do things.  I've made some progress towards fixing this (notably #109) but we need to finish that off by only setting `auto_build: true` on initial creation if `snapcraft.yaml` exists.
