### ISSUE TITLE
Successfully built points at a single architecture, the most recent one [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#302]
---

Copied from Trello card: https://trello.com/c/q8CRprwi/311-successfully-built-points-at-a-single-architecture-the-most-recent-one
Labels:

**Comment by matthewpaulthomas** [comment]
On Trello, Evan wrote:
> The successfully built link points off to a single build, which can be confusing since there are multiple architectures built for each git commit. Clicking on the link will show you the most recent successful build of all of the architectures. This means it will show you a different build from one moment to the next.

Bartek wrote:
> Yes, builds are per architecture, so a link to a single build will be pointing to one single architecture.
>
> Builds from LP don't contain any commit data yet, so we cannot group them by the commit ATM.
>
> 'Latest build' on dashboard links to the latest build (one architecture) as reported by Lauchpad.
>
> We have a separate card [#388] to implement 'Latest build' as per spec that defines different priorities to build statuses. Show latest build according to priority But these still would be single (per architecture) builds.

Bartek wrote:
> What would be a desired behaviour here? We can't easily group builds by git commit now because we don't have such data.
>
> The easiest 'workaround' I can think of is changing the link of latest build from enabled repository, so it doesn't link to a single build (build.snapcraft.io/user/repo/builds/1234) but to the repo page (build.snapcraft.io/user/repo/builds). This will show all builds for the repo, with latest on the top of the table (all the architectures will be visible).

**Comment by matthewpaulthomas** [comment]
I never specified that the “Latest build” cell should link anywhere in the first place. So following the spec would have avoided this problem!

However, it’s understandable that someone made it a link — firstly because most (soon all) other cells in the table do something when you click them, and secondly because it would be annoying to have “Built for publishing” or especially “Failed to build” not offer more details when you click them.

So, unless+until we can have a build page that shows the equivalent build for all architectures, I agree that the most reasonable thing to do would be to link to the repo page instead. [Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.5c3e9xiupuq5).
