### ISSUE TITLE
[add new repo] add message that private repos are not showing [5]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#309]
TODO:

- [x] Adding in the text about missing repos (org and private)
- [ ] Implement new tooltip component
- [ ] Implement simple text tooltip with info about org and private repos
- [ ] Decide how subscription for more info should work (our own or remote service)
- [ ] Access GH user email (ask for proper permissions, call emails API to get an email)
- [ ] Test handling private GH emails 

---

Copied from Trello card: https://trello.com/c/bxZEAhf4/176-add-new-repo-add-message-that-private-repos-are-not-showing
Labels:

**Comment by evandandrea** [comment]
We don't currently support private repos. People will wonder why their private repos are not visible on the select-repositories page, so:

1. Let's explain that it's not currently possible to add a private repo
1. If they need support for private repos they should contact us (we can ask IS for an email address specifically for fielding these). This will let us gauge interest.

**Comment by matthewpaulthomas** [comment]
I’d already designed (2) for [the case where you have no public repos at all](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.43owh6tjv12q) (#422): “Want to use a **private repo**? Sign up and we’ll e-mail you at {e-mail address} when we’ve got that working. ( Let me know )”

So now we need an equivalent design for if you have a mixture of public and private repos. My initial thought is that this would be a link from the “(private repos not shown)” note.

**Comment by evandandrea** [comment]
Agreed. I think that's a good spot for it.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.aw1ch3eqtp24): “Clicking ‘private repos not shown’ should open a popup containing the same [‘Want to use a private repo?…’ text and button](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=id.msdazl1vu8u7) as when you have no private repos at all. Clicking anywhere outside the popup should dismiss it.”

**Comment by jamiedawsonyoung** [comment]
### Specification for this flow: 
1. I use a spec tool which spits out a online viewable spec for the pages designed. The best thing to do is to download the whole folder [spec-export.zip](https://github.com/canonical-ols/build.snapcraft.io/files/867756/spec-export.zip) then open the html page in any browser and you should get the spec tool UI. By clicking through the pages on the left you'll find all the style and spacing values you need (hopefully). 

2. I've also added a link to the [flat visuals](https://www.dropbox.com/sh/jd6hnyacnep01bt/AAAtrzBxlwdwtZ54KCYUkOSHa?dl=0) as well.

There's some new styles in there but this issue is all about: 
- Adding in the text about missing repos (org and private) 
- Showing the pop-over link
- Building the pop-over with a text and a button for sign up.

FYI: I started with the [tooltip style](http://ubuntudesign.github.io/maas-gui-vanilla-theme/index.html) for Maas If that's useful to know.

Give me a shout if you have any questions!

**Comment by bartaz** [comment]
@jamiedawsonyoung @matthewpaulthomas 

Because of the dynamic tooltip (with action button) and sign-up feature this seems like much more than originally estimated [2].

I want to clarify some details around this signing up.

We show to the user their email address. I assume it's an email address from GitHub. What if user chooses not to share their GH email (which is possible in GH privacy options)?

What do we do with this email? Do we want to send anything to this email already (we currently don't have any means to do that) or just store the subscription in the database for later use?

**Comment by bartaz** [comment]
It seems to access GH user email we need to first ask for a permission to access it when user authorises the app (with `user:email` scope) and then use separate API call to get user email (as this data is not added to regular user API we currently use to get user name etc).

**Comment by magdalena-mirowicz** [comment]
@matthewpaulthomas @bartaz 

The decision to go forward is:
1) Update the design to simplify the build (use text field)  - Matthew could you look at it today please?

2) We need to provide a link to legal terms in the footer, which we do, and this covers our privacy policy

3) For storing emails - @nottrobin please update

**Comment by bartaz** [comment]
from IRC with @nottrobin 
> use this mailchimp form: http://canonical.us3.list-manage.com/subscribe?u=56dac47c206ba0f58ec25f314&id=381f5c55f1
> grab info out of it according to this post maybe? http://kb.mailchimp.com/lists/signup-forms/host-your-own-signup-forms

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#bookmark=kix.prg8c7su2lt4). Since the implementation is nearly done anyway, I’ll just take a screenshot of it rather than doing a new wireframe/mockup!

**Comment by magdalena-mirowicz** [comment]
@matthewpaulthomas makes sense
