### ISSUE TITLE
Distinguish table cell that was clicked on from others in the row [2]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#321]
In the “Repos to build and publish” table, when you click a cell that expands the row, there is no indication of which cell you clicked on.

This does not matter for Maas, where clicking any part of the row reveals the same stuff.

But it does matter for us, because clicking a row’s “Configured” cell reveals different stuff from the “Registered for publishing” cell.

_One_ possibility is as illustrated: highlighting just the clicked cell in the same color as the revealed panel, while leaving the row’s other cells in their original color.

---

Copied from Trello card: https://trello.com/c/emsmNfMS/336-distinguish-table-cell-that-was-clicked-on-from-others-in-the-row
Labels:

---

Scope of this task based on new visual design and as discussed in [comment below](#issuecomment-296981651):

Related to table cell highlighting - should be handled in this task:
- [x] removed grey background from the table
- [ ] added arrows icons in expandable cells
- [x] hover effects on cells
- [x] updated style of expanded row (borders, background)

Other table changes (can be covered in this issue):
- [x] updated link style (not blue until hovered)
- [x] updated spacing of the rows
- [x] possibly updated font size and weights

**Comment by matthewpaulthomas** [comment]
![repo list with non-matching names](https://cloud.githubusercontent.com/assets/19801137/23612053/c13da1da-0271-11e7-9c49-c3f0baaf1e8a.png)

**Comment by jamiedawsonyoung** [comment]
## Visual exploration: 
- Cell highlighted instead of row
- "Close chevron" to give affordance
- Helper text using the <small> tag
- All build statuses of table rows

![my-repos-table](https://cloud.githubusercontent.com/assets/6909617/23794733/8deceee2-0589-11e7-94ab-23588928975d.png)

@matthewpaulthomas How's this?

**Comment by matthewpaulthomas** [comment]
Looks good, with two niggles:
- Making the text bold may not work well in the case of the snap name, because it may alter the number of visible characters.
- I don’t think there should be a “close chevron”, for the same reason that dialogs shouldn’t have close buttons: their effect would be ambiguous. (For example, if you typed a snap name then clicked the chevron, would that try to register the name you’d typed, or not?) The case we’ve illustrated here is one of only two that don’t have buttons, so maybe they should just have a button, but that’s really a separate problem.

**Comment by jamiedawsonyoung** [comment]
@matthewpaulthomas okay, a new proposal.
- Reverse the colour in the table so the open panel becomes light grey. That way we can stretch the table to the full width (1030) and allow for more space for the snap name which we can utilize if the name gets longer when it goes up a weight. The colours and status icons look better on white too.
- Happy to remove the chevron :-)

![my-repos-table-2](https://cloud.githubusercontent.com/assets/6909617/23798029/99f1fdd4-059a-11e7-994a-22af79c5a628.png)

Another thought I had was the terminology for a unconfigured and unregistered repo. I wonder if something more like "Configure" and "Register" would be more instructional as to what the user needs to do? (just a thought)

**Comment by matthewpaulthomas** [comment]
Either way, I think the colour works and doesn’t require a grey strip around the outside. I’m more used to seeing a current area being lighter/brighter than others rather than darker/dimmer (for example, windows on OS X, and dialogs on Ubuntu Touch).

This report is just about the cell highlighting — please report other issues separately. :-)

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Distinguish table cell that was clicked on from others in the row](https://trello.com/c/o8EcVyed/593-distinguish-table-cell-that-was-clicked-on-from-others-in-the-row)

**Comment by magdalena-mirowicz** [comment]
@jamiedawsonyoung please add spec

**Comment by jamiedawsonyoung** [comment]
For visuals and interactions please see slide 29 – 40 of the [visual design deck](https://docs.google.com/a/canonical.com/presentation/d/1tge2i4paDDVTPAXHLWJgMioNmkEOxr7giVvy7nPILRU/edit?usp=sharing).

For the spec to make the changes. [Download this file](https://github.com/canonical-ols/build.snapcraft.io/files/919644/my-repos.zip), unzip it and open the index.html with a browser. You'll get the spec tool along with all the pages spec'd out. You should have everything you need…

**Comment by matthewpaulthomas** [comment]
Thanks Jamie!

**Comment by magdalena-mirowicz** [comment]
@matthewpaulthomas does it need any more design input or should it be moved to ready?

**Comment by matthewpaulthomas** [comment]
@magdalena-mirowicz As Jamie said, engineers should have everything they need for this now.

**Comment by bartaz** [comment]
Task breakdown based on new visual design linked in comments above:

Not related to table, but on same page:
- grey background under user profile in top of the page

Related to table:
- removed grey background
- updated spacing of the rows
- possibly updated font size and weights
- updates icon images (in configured, registered and build status columns)
- added arrows icons in expandable cells
- hover effects on cells
- updated style of expanded row (borders, background)
- changed button placement in dropdowns (in same line with rest of the content)
- register name input moved to dropdown - already tracked in #468
- updated layout of register name dropdown (possibly can be covered in #468)
- updated button styles (new cancel button style, new red Remove button)
