### ISSUE TITLE
[Add new repo] [Dashboard] Separate “Organization” column in repo table

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#342]
We might handle organizations another way

---

Copied from Trello card: https://trello.com/c/mdaVd1al/255-add-new-repo-dashboard-separate-organization-column-in-repo-table
Labels: design

**Comment by evandandrea** [comment]
The title of this is a bit confusing, so to clarify: Add support for organisations.

This will most likely take the form of a separate column of repositories on the select-repos ("Add…") page.

**Comment by matthewpaulthomas** [comment]
The title was Teresa’s suggestion for an initial, possibly temporary implementation, before we do a more thorough design.

The benefit would be that people would spend less time scanning repo names, since they could mostly ignore the “Organization” column.

Drawbacks I can think of:
- It would block us from implementing coherent sorting, since sorting by name would intermingle repos from different organizations
- If (for that reason) the long-term design was notably different, some users would have had to learn three designs rather than two.

**Comment by pmahnke** [comment]
Just mentioning, it is a pretty common git/github pattern to have the orgname/reponame as standard

**Comment by cjwatson** [comment]
Yeah, I think it's a mistake to deviate from how everyone else represents GitHub repositories.  For better or worse, orgname/reponame is what people expect to see pretty much everywhere.

**Comment by matthewpaulthomas** [comment]
Ok, following that feedback from @pmahnke and @cjwatson (as well as the drawbacks I mentioned) I’m going to set aside this suggestion. Handling organizations throughout the UI is covered by #132.
