### ISSUE TITLE
Don't let user change the snap name when you have snapcraft.yaml

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#344]
---

Copied from Trello card: https://trello.com/c/nRmWBtK3/227-don-t-let-user-change-the-snap-name-when-you-have-snapcraft-yaml
Labels:

**Comment by matthewpaulthomas** [comment]
Unfortunately Trello has no further details of this proposal or who made it. I’m closing it because, as far as I can tell, it would be counterproductive.

Sometimes you will legitimately want to change a snap name, for example, following a trademark dispute or other rebrand. If so, you have to change both the registered name and the snapcraft.yaml name. _If_ we enforced the order in which you did those things, changing the registered name first shouldn’t be prohibited — it should be required! Otherwise you might commit, to your repo, a name that then turns out not to be available.

It seems unlikely that people will change a snap’s registered name, to be different from the snapcraft.yaml name, by accident. But [the spec includes a warning](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.cihlhmeh60a0) just in case: “Builds will stop until you update the snapcraft.yaml to match.” I think that’s enough.
