### ISSUE TITLE
Only show duration header when build starts or completes

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#393]
Comments:

From @carla873, we should only show the duration header on the build page once there is text to put beneath it (the build has started or completed). It wasn't clear to her what "duration" meant in this context.

@matthewpaulthomas are you happy with that?

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/ogbek654/346-only-show-duration-header-when-build-starts-or-completes
Labels: copy to github

**Comment by matthewpaulthomas** [comment]
On the repo page we show “Previous builds” with the duration of each.

Above those, we show “Latest builds”. These should have the same column widths, so that they line up with the “Previous builds” table below. So they should also have a “Duration” column, even if it doesn’t contain anything.

The status table on the build page is one row of — and may eventually be an exact copy of — the “Latest builds” table on the repo page. It would be nice if it had the same column widths, but less important.

[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.lxvgcss3u749): “The table should be identical to the headers and equivalent row on the repo page, except that the “Duration” column should be invisible for a build that has not started yet.”

**Comment by matthewpaulthomas** [comment]
Explaining this to Teresa revealed an inconsistency. Once we show multiple architectures on the same build page, it will sometimes be the case that some of the architectures have started building while others have not. In this case, the “Duration” header will be present for the sake of those architectures that have started building. And it would be strange for one architecture’s duration to be presented differently depending on whether _other_ architectures have started building.

Therefore, I’ve reverted this change. The “Duration” header should be present regardless of whether any particular build has started, and the “Duration” cell should contain an em dash whenever it has not.
