### ISSUE TITLE
"Build took too long" status

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#420]
https://github.com/canonical-ols/build.snapcraft.io/issues/412 suggests that builds will time out after two hours. I don't see anything that would represent that state in [the API](https://api.launchpad.net/devel.html#snap_build) nor do I see text for it in [the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.ii93oqyp8hl8).

@cjwatson can you confirm that builds will get killed after two hours, and that we need a new build state to represent that? @matthewpaulthomas can you create copy for this?

**Comment by cjwatson** [comment]
No, that's not at all correct.

The current state is that *network access* for a build will stop working after two hours.  The build itself can take longer.

Although we unfortunately don't have great telemetry, anecdotally it was pretty rare for builds to hit the previous one-hour timeout.  Even if a snap build doesn't explicitly put all its downloading in the pull phase, the nature of things is that it normally downloads things it needs earlier rather than later.  The only builds that I ever heard of failing due to this were ones that were marginal (i.e. they worked sometimes, so must have been very close to the boundary) or ones that were a bit too slow on slower architectures (I heard of the odd problem like this with Maven-based builds on ARM).  So the intent is that two hours should be more than sufficient for network access from any legitimate builds while still providing a basic cut-off for abuse.  If it still proves to be insufficient then we'll revisit further; and the eventual intent is still to remove the proxy entirely, once we are able to allocate time for this sort of infrastructure maintenance work.

As far as BSI is concerned, all it would see in this case is a build failure, and it would be very difficult to represent it in any more structured way (because the actual error would be received by something deep in the build system stack that's specific to the kind of snap being built, and we have no control over how it bubbles up to the layers that we control).  So I don't think it's worth the considerable effort needed to parse and represent this as a particular build state, any more than the various other ways in which a build might fail.  At most, it might at some point be worth a FAQ-type document with pointers as to where you might start looking if your snap build fails in such-and-such a way.

Closing for now, since I think this was based on a mistaken assumption.  Thanks.

**Comment by evandandrea** [comment]
Thanks for the detailed clarification.

>
