### ISSUE TITLE
Gather metrics for KPI dashboard [2]

### ISSUE THREAD

**Issue by magdalena-mirowicz** [canonical-ols/build.snapcraft.io#446]
We need basic visibility on uptake and fall-off points, tracking how many developers are at each major step (github logged in, name registered, snap pushed to edge) from the KPI dashboard

**Comment by cjwatson** [comment]
@evandandrea Should this be a ratchet (e.g. "how many developers have ever registered any name via BSI"), or should the value drop back down if a developer removes all their snaps from BSI after once getting something all the way through the process?

It probably doesn't make very much difference to implementation difficulty (there are pros and cons either way), but I need to know before I start since it will probably affect the shape of the code.

**Comment by evandandrea** [comment]
I think we should track additions and deletions separately, and start with
just the former. We can add them together at the level of grafana when we
have both.

**Comment by cjwatson** [comment]
I've split the "developers with snaps pushed to edge" part of this out to a separate issue, #517, since it involves a somewhat different kind of work from the others.
