### ISSUE TITLE
Consider adding "Add repositories" link in the header

### ISSUE THREAD

**Issue by earnubs** [canonical-ols/build.snapcraft.io#559]
Instinctively I'm looking for the add repositories button in the header, not within the page.

**Comment by jamiedawsonyoung** [comment]
Hi @earnubs I think this will be less of a issue when the header is simpler.

**Comment by matthewpaulthomas** [comment]
Thanks for the suggestion, but things have changed since:
- There is no longer a link to “My repos” (then called “Dashboard”) in the header, making it less plausible that other top-level actions should be there either.
- We now plan to integrate build.snapcraft.io with the rest of snapcraft.io, making it less likely that the header will contain _anything_ app-specific other than whether you’re signed in.
