### ISSUE TITLE
Organisations: Tidy up attribution metrics to support organisation repositories [2]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#621]
Currently the GitHub username is inferred from the repository name (<user>/<repository>) in some places. This will no longer work once we are dealing with organisation repositoriess. This should be fixed so attribution metrics continue to reflect the current user.

**Comment by cjwatson** [comment]
I used the repository name for this because there wasn't really any other obvious way to go about this (in some cases we need this from a webhook context, for instance, where no store credentials are available).

However, it doesn't have to be perfect, so one reasonable if hacky approach would be to remember the admin who registered the snap in memcached and credit metrics to them.  The publisher of a snap can be reassigned in the store, and we wouldn't notice this, but the relevant metrics are essentially all setup tasks so this is probably OK; it'd just need clear internal documentation so that we don't later get confused and use that data for something inappropriate.
