### ISSUE TITLE
Organisations: Prevent other organisation members from disabling snap auto building [2]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#646]
When the user wasn't the one that setup an organisation snap, they can't disable it.

**Comment by matthewpaulthomas** [comment]
Straw person proposal: If you aren’t the person who “set up” the repo, we could still show you the Delete icon. But when you click it, instead of getting the Cancel and Delete buttons, we’d tell you who set it up, and suggest that you go talk to them. Does that seem reasonable?

Question: What do we mean by “set up”, exactly? Is this something we should do for every organization repo, _or_ just for those repos that have a registered name?

**Comment by evandandrea** [comment]
Your proposal seems reasonable to me.

I think to keep things simple, for now let's make it for every organisation repo. If Robin adds CanonicalLtd/snappy-docs, then it's read-only on Carla's dashboard. She cannot register a name for it even if Robin hasn't. She can click the delete icon, but doing so pops up your suggested text.

**Comment by cjwatson** [comment]
An important consideration that I discovered after talking to Natalia last week is that, in the general case, the store won't tell us who is the publisher of a particular snap, for privacy reasons.  (The new design for organisations in BSI per Mark is that the store doesn't (yet?) have any idea about the organisational relationships, so we can't say that the store will expose this information only to other admins; and I don't think there's any way that we can work around this by remembering the publisher in BSI, because it might be reassigned later on the store side.)

In the case where a snap has reached the stable channel, we can get this information in the same way that `snap info` does.  So it sounds like we'll be able to show the publisher in some cases, but not in every case.

Can we accommodate this in the design?

**Comment by cjwatson** [comment]
@evandandrea Perhaps counterintuitively, your "to keep it simple" proposal actually makes things more complicated.  There's currently no difference in the data we store for a repository until the point when the name is registered (and no very obvious place to store data that would differ).  It would be significantly easier to implement if we decided that this would just be for repositories with a registered name.

**Comment by nottrobin** [comment]
@cjwatson if we retrieve information in the same way that `snap info` does, won't we only get the publisher's namespace, rather than their name? (e.g. the `upload-assets` snap's "publisher" is `canonicalwebteam`, but the SSO username is actually `cwebteam`) Is that of any use to us?

Are we not even able to tell if you own a particular snap if you are logged in to SSO?

**Comment by evandandrea** [comment]
I believe I made the suggestion in the Friday meeting that we start tracking in the build.snapcraft.io database what repos you've added to the dashboard. I think your point that the name might get reassigned makes that a bad idea (without needing to debate the jump to stateful).

So what do we think of the following when you click the rubbish bin:
1. SSO dance, similar to name registration
1. If you are the publisher (not a collaborator), remove
1. If you are not the publisher, throw up instructions that say, "contact the publisher; if you don't know who that is, contact Canonical."

To be clear, for GA I think it's unlikely we'll get to these GitHub issues that form the idea of "show repos on my dashboard that I could debug and fix."

**Comment by cjwatson** [comment]
@nottrobin Technically I guess so, although I think namespaces and usernames are eventually due to be unified.  And no, SSO login doesn't help.

@evandandrea Sounds reasonable.  We can always refine from there later.

**Comment by cjwatson** [comment]
@nottrobin Actually, I misread what you wrote.  We can tell whether the user themself registered a given snap name (we already do that somewhere else, I think - the method is a bit hacky but it works), just not who registered it if it isn't the user themself.

**Comment by nottrobin** [comment]
Yep so it sounds like it's unwise to try to guess who registered a snap, we should only bother ourselves with whether the current user owns it. So @evandandrea's suggestion sounds good.

**Comment by bartaz** [comment]
Knowing if current user registered the name requires them to be signed in to SSO.
So remove action will require being sign in to SSO.

We can do it in similar way we do name registering - if you are not signed in instead of 'Remove' button we show 'Sign in' button and some copy saying (to remove the snap you need to be signed in to the store). And only after they return from SSO we will either show 'Remove' button (if they registered the name) or tell them that they cannot remove it and should contact the publisher.

**Comment by matthewpaulthomas** [comment]
If we followed exactly the same approach as registering a name — something like “To remove this repo, you need to sign in as the person who registered the name” with a “Sign in…” button — then we run the risk that some people would end up going through the whole process of creating an Ubuntu One account, so that they could sign in … only for us to tell them that [they couldn’t remove the repo after all](http://peanuts.wikia.com/wiki/Football_gag).

That unpleasantness would be much less likely if we could say “To remove this repo, you need to sign in as {ID of person who registered the name}”, but if I understand the discussion above, we can’t do that.

So, maybe the best we can do is something like “You can remove this repo only if you registered the name {snap-name}”.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.q8fitjuvz7vi):
> **If the repo has a registered name, and you are not signed in, the text and buttons should be:**
>> You can remove this repo only if you registered the name {snap-name}.
>> Cancel • Sign in…
>
> **If the repo has a registered name, and you are signed in as someone who didn’t register the name, there should be no buttons, and the text should be:**
>> To remove this repo, contact the person who registered the name {snap-name}.
>
> **In all other cases…**
