### ISSUE TITLE
No-op snap takes 1.5 min to build, 6.5 minutes to publish

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#717]
Publishing takes an oddly long amount of time (6.5 minutes) off the smallest snap. Shouldn't this be seconds at most?

<img width="1440" alt="screen shot 2017-05-04 at 15 53 46" src="https://cloud.githubusercontent.com/assets/1523179/25722372/f9d5b5de-30e1-11e7-8291-e93d72634bf9.png">
<img width="1440" alt="screen shot 2017-05-04 at 15 50 22" src="https://cloud.githubusercontent.com/assets/1523179/25722383/00753946-30e2-11e7-8618-c441f137bc90.png">

**Comment by cjwatson** [comment]
Could you re-file this as a bug against Launchpad itself, please?  I don't mind keeping track here of issues that span both BSI itself and other systems it uses, but when they're solely in another system I think it makes more sense to file them directly in that other system's bug tracker.

The background for this is that publishing involves multiple steps: we have to do the equivalent of `snapcraft push` and then the equivalent of `snapcraft release`, and between those we have to wait for the store to finish scanning the upload, which is an asynchronous job and takes an undetermined amount of time.  Rather than polling and thus taking up a worker slot in Launchpad for that undetermined amount of time, we retry the job later with a one-minute delay up to a maximum of 20 times.

There are various things that we could look at to reduce the latency of this process (which aren't all mutually-exclusive, and we may not know the best strategy until we do some more analysis):

* Unlike the initial job, retries don't seem to be handled by celery for some reason, but instead are picked up by the fallback cron job some time later.  This is the source of most of the unnecessary delay, and is probably just a simple bug somewhere.  Assuming that the store scans the upload reasonably promptly, we could cut the typical delay for small snaps down to a little over a minute by getting celery to pick up the retries.
* We could consider having the job poll for a short time after it pushes the snap, which would cut out almost all the extra latency in the case that the store manages to scan it immediately.  This may be a good idea, but probably only if the store typically does in fact manage quick scans; otherwise we'd be tying up workers for longer and degrading overall system performance.
* We could try some kind of exponential backoff approach, so that the first retries happen more quickly.
* We could look at having the store tell us when it's done by way of a webhook.  This seems like the most elegant approach, but it's also a lot of work in that it requires implementing webhook sending in the store and webhook receiving in Launchpad.

**Comment by evandandrea** [comment]
Yup, happy to. Filed https://bugs.launchpad.net/launchpad/+bug/1689282.

Thanks as ever for the detailed explanation of the underlying issue.

**Comment by cjwatson** [comment]
Thanks.  Closing this one, then.
