### ISSUE TITLE
Unauthorised when trying to re-use snap name

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#719]
I'm getting a 401 when trying to use a name I already own:

<img width="1440" alt="screen shot 2017-05-04 at 20 31 24" src="https://cloud.githubusercontent.com/assets/1523179/25730203/b86df3b4-3108-11e7-947f-beb70f7496a6.png">

**Comment by evandandrea** [comment]
Signing out of build.staging.snapcraft.io and signing back in fixed this.

**Comment by bartaz** [comment]
I think I might have seen something similar when I was signed in for very long.

My first guess is that store macaroon expires while BSI still assumes user is signed in to the store.
Not sure at this point if there is any easy way for us to detect if macaroon is still valid without trying to call store API...

cc: @cjwatson

**Comment by bartaz** [comment]
Our current package upload macaroon lifetime is 7200 which I believe is in seconds, so would give 2 hours.

**Comment by cjwatson** [comment]
Ah, I figured it out - it's because we switched to the forked store in f55ff8c167f265433d6e0459021cd5721009c97a, so we're now expecting the macaroon to be issued with its location set to `dashboard.snapcraft.io`; but it's in fact still issued with the location set to `myapps.developer.ubuntu.com` (presumably because it would take some compatibility faff to switch).  This bug therefore means that in general we're failing to check expiry of the store macaroon at the moment.

I think the right answer is probably to just check for an expires caveat matching the location field of the macaroon rather than expecting that the macaroon is going to be issued from the host that we think we're contacting.
