### ISSUE TITLE
Repository paging in select-repositories is broken

### ISSUE THREAD

**Issue by earnubs** [canonical-ols/build.snapcraft.io#787]
Paged views are sliced incorrectly...

**Comment by bartaz** [comment]
To give this more context.

We are filtering out repositories that user is not admin of, but paging links that we get from GH assume whole list of repositories.

So when there are many repos that user is not admin of paging may return very unexpected results. Some pages may contain just few repos, some may be completely empty.

**Comment by bartaz** [comment]
There doesn't seem to be an quick way to fix it.

We need to rely on GH pagination (because we use their API), but we are showing filtered results on our side - so pages don't match.

Another 'solution' - at least temporary - could be to show ALL the repos on the list (so paging would work correctly - all repos would be visible), but disable those where user is not admin.
We could grey-out the disabled one and show some message (maybe just a tooltip) to explain that this repo can't be added because user is not admin.

**Comment by earnubs** [comment]
Pagination links are set by github, when you filter the list, the pagination is wrong and the client cannot know the correct pagination until it has seen the entire list of repos.

**Comment by earnubs** [comment]
@bartaz I think you could also move those disabled repos to the end of the list.

**Comment by bartaz** [comment]
@earnubs possibly - but again, not until we know the whole list

**Comment by earnubs** [comment]
@bartaz Ah yes, true. It would look odd having this small group at the bottom follow you from 'next' to 'next' :)

**Comment by matthewpaulthomas** [comment]
Disabling would be fine as a temporary solution. (And probably as a long-term solution, too, with a bit more explanation.)
